version: "3.3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=Y
  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: secret
      - MYSQL_DATABASE: development
    volumes:
      - ./data/mysql:/var/lib/mysql/data
