version: "3.3"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - ACCEPT_EULA=Y
    volumes: 
      - ./data/myssql:/var/opt/mssql
  mysql:
    image: mysql:5.7.28
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=development
    volumes:
      - ./data/mysql:/var/lib/mysql/data
  proyecto01:
    image: proyecto-01
    restart: always
    build:
      context: ./proyecto-01
      dockerfile: Dockerfile
    volumes:
      - ./proyecto-01:/var/www/html
    depends_on:
      - mysql
  proxy:
    image: nginx:latest
    restart: always
    volumes:
      - ./sites:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - proyecto01
